import NavBar from "@/Components/NavBar/NavBar"

export const metadata = {
  title: 'Momin Food Products',
  description: 'Generated by create next app',
}


export default function UsersLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
  
    return (
        <div>
            <NavBar/>
            {children}
        </div>
    )
  }