import Loading from '@/Utility/Loading/page';
import ContextProvider from './Context/store';
// import '../Database/MongoConfig/MongoConfig';

import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <ContextProvider>
        <body className={inter.className}>
          <Loading>
            {children}
          </Loading>
        </body>
      </ContextProvider>
    </html>
  )
}
